cats/urls.py
from django.urls import path

from cats import views as v

app_name = 'cats'
urlpatterns = [
    path('', v.CatListView.as_view(),  name='index'),
    path('main/create', v.CatCreateView.as_view(), name='cat_create'),
    path('main/<int:pk>/update', v.CatUpdateView.as_view(), name='cat_update'),
    path('main/<int:pk>/delete', v.CatDeleteView.as_view(), name='cat_delete'),
    path('lookup/', v.BreedListView.as_view(), name='breed_list'),
    path('lookup/create/', v.BreedCreateView.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update', v.BreedUpdateView.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete', v.BreedDeleteView.as_view(), name='breed_delete'),
]

mysite/urls.py
import os

from django.contrib import admin, auth
from django.urls import include, path, re_path
from django.views.static import serve

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('', include('home.urls')),
    path('cats/', include('cats.urls')),
    path('autos/', include('autos.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('hello/', include('hello.urls')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    re_path(r'^site/(?P<path>.*)$', serve,
         {'document_root': SITE_ROOT, 'show_indexes': True},
         name='site_path'
    ),
]

cats/models.py
from django.core.validators import MinLengthValidator
from django.db.models import Model, CharField, PositiveIntegerField, ForeignKey, CASCADE

class Breed(Model):
    name = CharField(
            max_length=200,
            validators=[MinLengthValidator(2, 'Breed must be greater than 1 character')]
            )
    
    def __str__(self):
        return self.name

class Cat(Model):
    nickname = CharField(
            max_length=200,
            validators=[MinLengthValidator(2, 'Nickname must be greater than 1 character')]
            )
    weight = PositiveIntegerField()
    foods = CharField(max_length=300)
    breed = ForeignKey('Breed', on_delete=CASCADE, null=False)
    
    def __str__(self):
        return self.nickname

cats/views.py
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from cats.models import Breed, Cat 

class BreedListView(LoginRequiredMixin, ListView):
    model = Breed

class CatListView(LoginRequiredMixin, ListView):
    model = Cat

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['breed_count'] = len(Breed.objects.all())
        return ctx

class BreedMixin:
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy('cats:index')

class BreedCreateView(BreedMixin, LoginRequiredMixin, CreateView):
    pass

class BreedUpdateView(BreedMixin, LoginRequiredMixin, UpdateView):
    pass

class BreedDeleteView(BreedMixin, LoginRequiredMixin, DeleteView):
    pass

class CatMixin:
    model = Cat
    fields = '__all__'
    success_url = reverse_lazy('cats:index')

class CatCreateView(CatMixin, LoginRequiredMixin, CreateView):
    pass

class CatUpdateView(CatMixin, LoginRequiredMixin, UpdateView):
    pass

class CatDeleteView(CatMixin, LoginRequiredMixin, DeleteView):
    pass

cats/templates/cats/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="dj4e-code" content="42172675438122">
    <meta name="dj4e" content="2b12fa2d64abbe1942370ba7f5e9226b">
    <title>{% block title %}Cats Crud{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
      <h1>Cats CRUD</h1>
    <div class="container">{% block content %}{% endblock %}</div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

cats/templates/cats/breed_confirm_delete.html
{% extends "cats/base.html" %}
{% block content %}
<h2>Really delete {{ breed }}?</h2>
<form action="" method="POST">
  {% csrf_token %}
  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <button type="submit" class="btn btn-danger">Yes, Delete</button>
    <button type="button" class="btn btn-primary" onclick="navigation.back()">Cancel</button>
  </div>
</form>
{% endblock %}

cats/templates/cats/breed_form.html
{% extends "cats/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form action="" method="post">
  <legend>Add a new breed</legend>
  {% csrf_token %}
  {{ form|crispy }}
  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <button type="submit" class="btn btn-success">Submit</button>
    <button type="button" onclick="navigation.back()" class="btn btn-danger">Cancel</button>
  </div>
</form>
{% endblock %}

cats/templates/cats/breed_list.html
{% extends "cats/base.html" %}
{% block content %}
{% if breed_list %}
<ul class="list-group mb-3">
    {% for breed in breed_list %}
    <li class="list-group-item d-flex flex-wrap align-items-center text-break">
      {{ breed }}
      <div class="ms-auto btn-group">
        <a class="btn btn-primary" href="{% url 'cats:breed_update' breed.id %}">Update</a>
        <a class="btn btn-danger" href="{% url 'cats:breed_delete' breed.id %}">Delete</a>
      </div>
    </li>{% endfor %}
</ul>
{% else %}
<h2>No breeds found.</h2>
{% endif %}
<a class="btn btn-primary" href="{% url 'cats:breed_create' %}">Add a breed</a>
<a class="btn btn-primary" href="{% url 'cats:index' %}">Back to cats</a>
{% endblock %}

cats/templates/cats/cat_confirm_delete.html
{% extends "cats/base.html" %}
{% block content %}
<h2>Really delete {{ cat }}?</h2>
<form action="" method="POST">
  {% csrf_token %}
  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <button type="submit" class="btn btn-danger">Yes, Delete</button>
    <button type="button" class="btn btn-primary" onclick="navigation.back()">Cancel</button>
  </div>
</form>
{% endblock %}

cats/templates/cats/cat_form.html
{% extends "cats/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form action="" method="post">
  <legend>add a new cat</legend>
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit" class="btn btn-success">Submit</button>
  <button type="button" onclick="navigation.back()" class="btn btn-danger">Cancel</button>
</form>
{% endblock %}

cats/templates/cats/cat_list.html
{% extends "cats/base.html" %}
{% block content %}
{% if cat_list %}
<ul class="list-group mb-3">
  {% for cat in cat_list %}
  <li class="list-group-item d-flex flex-wrap align-items-center text-break">
    {{ cat }}
    <div class="ms-auto btn-group">
      <a class="btn btn-primary" href="{% url 'cats:cat_update' cat.id %}">Update</a>
      <a class="btn btn-danger" href="{% url 'cats:cat_delete' cat.id %}">Delete</a>
    </div>
  </li>{% endfor %}
</ul>
{% else %}
<h2>No cats yet.</h2>
{% endif %}
{% if breed_count %}
<a class="btn btn-primary" href="{% url 'cats:cat_create' %}">Add a cat</a>
{% else %}
<h2>Add some breeds first</h2>
{% endif %}
<div class="btn-group">
<a class="btn btn-primary" href="{% url 'cats:breed_create' %}">Add a breed</a>
<a class="btn btn-primary" href="{% url 'cats:breed_list' %}">View breeds ({{breed_count}})</a>
</div>
{% endblock %}